services:
  lizing-parser-sber:
    build:
      context: ./lizing-parser-sber
    container_name: lizing-parser-sber
    depends_on:
      - db
    restart: unless-stopped

  lizing-parser-vtb:
    build:
      context: ./lizing-parser-vtb
    container_name: lizing-parser-vtb
    depends_on:
      - db
    restart: unless-stopped

  lizing-migrations:
    build:
      context: ./migrations
    container_name: migrations
    depends_on:
      - db
    restart: no
    command: >
      /bin/sh -c "
      alembic revision --autogenerate &&
      alembic upgrade head
      "

  db:
    image: postgres:16
    container_name: lizing-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

volumes:
  pgdata: