services:
  parser-sber:
    build:
      context: ./lizing-parser-sber
    container_name: lizing-parser-sber
    depends_on:
      - db
    restart: no
    env_file:
      - .env.prod
    volumes:
      - ./lizing-parser-sber/logs:/src/logs
      - ./lizing-parser-sber/screenshots:/src/screenshots
      - ./lizing-parser-sber/pages:/src/pages

  parser-vtb:
    build:
      context: ./lizing-parser-vtb
    container_name: lizing-parser-vtb
    depends_on:
      - db
    restart: no
    env_file:
      - .env.prod

  migrations:
    build:
      context: ./migrations
    container_name: lizing-migrations
    depends_on:
      - db
    restart: no
    env_file:
      - .env.prod
    command: >
      /bin/sh -c "
      alembic revision --autogenerate &&
      alembic upgrade head
      "

  db:
    image: postgres:16
    container_name: lizing-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - "5001:5432"
    restart: unless-stopped

volumes:
  pgdata: